In [1]:
import numpy as np
import math


Testing numpy functions 

In [29]:

x = np.linspace(1, 3, 3)
print(x)

[1. 2. 3.]


In [24]:
t = np.linspace(4, 10, 3)
print(t)

[ 4.  7. 10.]


In [30]:
X, T = np.meshgrid(x,t)
print(X)
print(T)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[ 4.  4.  4.]
 [ 7.  7.  7.]
 [10. 10. 10.]]


In [45]:

U = [np.pi, 2*np.pi, 3*np.pi]
print(U)

T = np.around(np.sin(U), decimals=10)

print(np.pi)
print(T)

[3.141592653589793, 6.283185307179586, 9.42477796076938]
3.141592653589793
[ 0. -0.  0.]
